import type { GitHubClient } from '../github/client.js';
import type { CreatePrInput, PullRequestResult } from '../types.js';

export async function handleCreatePr(
  input: CreatePrInput,
  client: GitHubClient,
): Promise<PullRequestResult> {
  const baseBranch = input.base_branch ?? 'main';

  await client.createBranch(input.repo_url, input.branch, baseBranch);

  for (const file of input.files) {
    await client.createOrUpdateFile(
      input.repo_url,
      file.path,
      file.content,
      `feat(tests): add ${file.path} via ClaudeTest`,
      input.branch,
    );
  }

  const fileList = input.files.map((f) => `- \`${f.path}\``).join('\n');
  const prBody = [
    '## ClaudeTest — Generated Tests',
    '',
    `This PR was automatically generated by [ClaudeTest](https://github.com/your-org/claude-enterprise-testing).`,
    '',
    '### Files added',
    fileList,
    '',
    '### Review checklist',
    '- [ ] Verify test scenarios match the intended behaviour',
    '- [ ] Run tests locally before merging',
    '- [ ] Update selectors if the UI has changed since generation',
  ].join('\n');

  const pr = await client.createPr(
    input.repo_url,
    input.title,
    input.branch,
    baseBranch,
    prBody,
  );

  return {
    pr_number: pr.number,
    html_url: pr.html_url,
    title: input.title,
    branch: input.branch,
  };
}
